let nodes = [
  { category: 0, name: "大万号", value: 12 },
  { category: 0, name: "冠字号", value: 10 },

  { category: 0, name: "轴号", value: 10 },

  { category: 0, name: "工艺质量管理平台", value: 15 },

  { category: 3, name: "物理站", value: 8 },
  { category: 3, name: "化验站", value: 8 },
  { category: 1, name: "钞纸机检", value: 8 },
  { category: 1, name: "钞纸工艺", value: 8 },
  { category: 3, name: "机读防伪指标", value: 8 },
  { category: 3, name: "外观指标", value: 8 },
  { category: 3, name: "机检在线抽查", value: 8 },
  { category: 3, name: "损纸误废", value: 8 },
  { category: 3, name: "批量报废", value: 8 },
  { category: 3, name: "切纸机生产原始信息", value: 8 },

  { category: 1, name: "凹印在线检测", value: 8 },
  { category: 1, name: "印钞装箱系统", value: 8 },
  { category: 1, name: "OCR系统", value: 8 },

  { category: 1, name: "胶凹离线检测", value: 8 },
  { category: 1, name: "机台作业", value: 8 },
  { category: 1, name: "质量综合管理系统", value: 8 },
  { category: 1, name: "号码三合一", value: 8 },
  { category: 1, name: "图像判废", value: 8 },
  { category: 1, name: "清分机检", value: 8 },
  { category: 1, name: "废品分析", value: 8 },
  { category: 1, name: "在线清数", value: 8 },
  { category: 1, name: "印钞特抽", value: 8 },
  { category: 1, name: "防伪指标", value: 8 },
  { category: 1, name: "库管信息", value: 8 },
  { category: 2, name: "大张数", value: 3 },
  { category: 2, name: "识别状态", value: 3 },
  { category: 2, name: "拒识数", value: 3 },
  //   { category: 2, name: "生产时间", value: 3 },
  { category: 2, name: "识别时间", value: 3 },
  { category: 2, name: "成品率", value: 3 },
  { category: 2, name: "作废率1", value: 3 },
  { category: 2, name: "IPP数", value: 3 },
  { category: 2, name: "缺陷数", value: 3 },
  { category: 2, name: "抽检开位", value: 3 },
  { category: 2, name: "抽检量", value: 3 },
  { category: 2, name: "废品类型", value: 3 },
  { category: 2, name: "作废工序", value: 3 },
  { category: 2, name: "作废开数", value: 3 },
  { category: 2, name: "封皮数", value: 3 },
  { category: 2, name: "作废率2", value: 3 },
  { category: 2, name: "出库时间", value: 3 },
  { category: 2, name: "出库人员", value: 3 },
  { category: 2, name: "机台", value: 3 },
  { category: 2, name: "入库时间", value: 3 },
  { category: 2, name: "入库人员", value: 3 },
  { category: 2, name: "胶正得分", value: 3 },
  { category: 2, name: "胶背得分", value: 3 },
  { category: 2, name: "凹正得分", value: 3 },
  { category: 2, name: "凹背得分", value: 3 },
  { category: 2, name: "印码得分", value: 3 },
  { category: 2, name: "裁切得分", value: 3 },
  { category: 2, name: "纸张得分", value: 3 },
  { category: 2, name: "评价总分", value: 3 },
  { category: 2, name: "竖号码", value: 3 },
  { category: 2, name: "OVMI", value: 3 },
  { category: 2, name: "安全线2", value: 3 },
  { category: 2, name: "W信号", value: 3 },
  { category: 2, name: "荧光亮度", value: 3 },
  { category: 2, name: "SM值", value: 3 },
  { category: 2, name: "磁性", value: 3 },
  { category: 2, name: "安全线1", value: 3 },
  { category: 2, name: "人员类型", value: 3 },
  { category: 2, name: "机长1", value: 3 },
  { category: 2, name: "机长2", value: 3 },
  { category: 2, name: "机长3", value: 3 },
  { category: 2, name: "机长4", value: 3 },
  //   { category: 2, name: "机台", value: 3 },
  { category: 2, name: "检测时间", value: 3 },
  { category: 2, name: "总分", value: 3 },
  { category: 2, name: "墨色", value: 3 },
  { category: 2, name: "接线", value: 3 },
  { category: 2, name: "套印", value: 3 },
  { category: 2, name: "混色", value: 3 },
  { category: 2, name: "防复印圈", value: 3 },
  { category: 2, name: "对印", value: 3 },
  { category: 2, name: "人工实废", value: 3 },
  { category: 2, name: "机检实废", value: 3 },
  { category: 2, name: "机检误废", value: 3 },
  { category: 2, name: "实废大张", value: 3 },
  { category: 2, name: "未检数", value: 3 },
  { category: 2, name: "实废小开", value: 3 },
  { category: 2, name: "拆包量", value: 3 },
  { category: 2, name: "实废图像1", value: 3 },
  { category: 2, name: "实废图像2", value: 3 },
  { category: 3, name: "小张核查", value: 6 },
  { category: 3, name: "码后核查", value: 6 },
  { category: 2, name: "荧光缺陷1", value: 3 },
  { category: 2, name: "号码缺陷1", value: 3 },
  { category: 2, name: "荧光缺陷2", value: 3 },
  { category: 2, name: "号码缺陷2", value: 3 },
  { category: 2, name: "印码号1", value: 3 },
  { category: 2, name: "印码号2", value: 3 },
  { category: 2, name: "印码号3", value: 3 },
  { category: 2, name: "印码号4", value: 3 },
  { category: 2, name: "印码号5", value: 3 },
  { category: 2, name: "印码号6", value: 3 },
  { category: 2, name: "印码号", value: 3 },
  { category: 2, name: "实废类型1", value: 3 },
  { category: 2, name: "实废数1", value: 3 },
  { category: 2, name: "漏废数1", value: 3 },
  { category: 2, name: "大张废1", value: 3 },
  //   { category: 2, name: "实废类型1", value: 3 },
  //   { category: 2, name: "实废数1", value: 3 },
  //   { category: 2, name: "漏废数1", value: 3 },
  //   { category: 2, name: "大张废1", value: 3 },
  { category: 2, name: "开位1", value: 3 },
  { category: 2, name: "宏区编号1", value: 3 },
  { category: 2, name: "好品率1", value: 3 },
  { category: 2, name: "缺陷条数1", value: 3 },
  { category: 2, name: "核查剔废率1", value: 3 },
  { category: 2, name: "正面缺陷1", value: 3 },
  { category: 2, name: "背面缺陷1", value: 3 },
  { category: 2, name: "透视缺陷1", value: 3 },
  //   { category: 2, name: "实废类型2", value: 3 },
  { category: 2, name: "实废数2", value: 3 },
  //   { category: 2, name: "漏废数2", value: 3 },
  { category: 2, name: "大张废2", value: 3 },
  { category: 2, name: "实废类型2", value: 3 },
  //   { category: 2, name: "实废数2", value: 3 },
  { category: 2, name: "漏废数2", value: 3 },
  //   { category: 2, name: "大张废2", value: 3 },
  { category: 2, name: "开位2", value: 3 },
  { category: 2, name: "宏区编号2", value: 3 },
  { category: 2, name: "好品率2", value: 3 },
  { category: 2, name: "缺陷条数2", value: 3 },
  { category: 2, name: "核查剔废率2", value: 3 },
  { category: 2, name: "正面缺陷2", value: 3 },
  { category: 2, name: "背面缺陷2", value: 3 },
  { category: 2, name: "透视缺陷2", value: 3 },
  { category: 3, name: "物料信息", value: 5 },
  { category: 3, name: "印版/色模", value: 4 },
  { category: 2, name: "编号", value: 3 },
  { category: 2, name: "印量", value: 3 },
  { category: 3, name: "油墨", value: 4 },
  { category: 2, name: "批次", value: 3 },
  { category: 2, name: "名称", value: 3 },
  { category: 2, name: "用量", value: 3 },
  { category: 3, name: "耗材", value: 4 },
  { category: 3, name: "生产信息", value: 5 },
  { category: 2, name: "机型", value: 3 },
  { category: 2, name: "班组", value: 3 },
  { category: 2, name: "班次", value: 3 },
  //   { category: 2, name: "生产时间", value: 3 },
  //   { category: 2, name: "检测时间", value: 3 },
  { category: 2, name: "产量", value: 3 },
  { category: 2, name: "工序1", value: 3 },
  { category: 2, name: "工序2", value: 3 },
  { category: 2, name: "作业记录", value: 3 },
  { category: 2, name: "大万号1", value: 3 },
  { category: 2, name: "大万号2", value: 3 },
  //   { category: 2, name: "大万号3", value: 3 }

  { category: 2, name: "箱号", value: 3 },
  { category: 2, name: "首张印码号", value: 3 },
  { category: 2, name: "装箱时间", value: 3 },
  { category: 2, name: "装箱机台", value: 3 },

  { category: 2, name: "识码时间", value: 3 },
  { category: 2, name: "实际开包量", value: 3 },
  { category: 2, name: "多取出数", value: 3 },
  { category: 2, name: "未取出数", value: 3 },
  { category: 2, name: "缺陷开数", value: 3 },

  { category: 2, name: "喷码号", value: 3 },
  { category: 2, name: "抽样张数", value: 3 },

  { category: 2, name: "检封裁切人工评分", value: 3 },

  { category: 2, name: "纸机好纸率", value: 3 },
  { category: 2, name: "切纸机好纸率", value: 3 },
  { category: 2, name: "纸机好纸数", value: 3 },
  { category: 2, name: "切纸机好纸数", value: 3 },
  { category: 2, name: "切纸机异常品数", value: 3 },
  { category: 2, name: "一次封包率", value: 3 },
  { category: 2, name: "返工率", value: 3 },

  { category: 2, name: "过程质量控制水平", value: 3 }
];

let links = [
  { source: "冠字号", target: "大万号", weight: 4, name: "唯一对应" },
  { source: "大万号", target: "冠字号", weight: 4 },
  { source: "在线清数", target: "大万号1", weight: 1 },
  { source: "在线清数", target: "大张数", weight: 1 },
  { source: "在线清数", target: "识别状态", weight: 1 },
  { source: "在线清数", target: "拒识数", weight: 1 },
  { source: "在线清数", target: "识别时间", weight: 1 },
  { source: "清分机检", target: "大万号2", weight: 1 },
  { source: "清分机检", target: "成品率", weight: 1 },
  { source: "清分机检", target: "作废率1", weight: 1 },
  { source: "清分机检", target: "IPP数", weight: 1 },
  { source: "清分机检", target: "缺陷数", weight: 1 },
  { source: "清分机检", target: "印码号6", weight: 1 },
  { source: "清分机检", target: "抽检开位", weight: 1 },
  { source: "清分机检", target: "抽检量", weight: 1 },
  { source: "清分机检", target: "实废数2", weight: 1 },
  { source: "清分机检", target: "实废类型2", weight: 1 },
  { source: "废品分析", target: "大万号", weight: 2 },
  { source: "废品分析", target: "废品类型", weight: 2 },
  { source: "废品分析", target: "作废工序", weight: 2 },
  { source: "废品分析", target: "机长1", weight: 2 },
  { source: "废品分析", target: "作废开数", weight: 2 },
  { source: "废品分析", target: "封皮数", weight: 2 },
  { source: "废品分析", target: "作废率2", weight: 2 },
  { source: "废品分析", target: "漏废数2", weight: 2 },
  { source: "库管信息", target: "大万号", weight: 2 },
  { source: "库管信息", target: "出库时间", weight: 2 },
  { source: "库管信息", target: "出库人员", weight: 2 },
  { source: "库管信息", target: "入库时间", weight: 2 },
  { source: "库管信息", target: "入库人员", weight: 2 },
  { source: "库管信息", target: "机长2", weight: 2 },
  { source: "库管信息", target: "工序2", weight: 2 },
  { source: "印钞特抽", target: "印码号", weight: 1 },
  { source: "印码号", target: "防伪指标", weight: 1 },
  { source: "印钞特抽", target: "冠字号", weight: 2 },
  { source: "印钞特抽", target: "印码号3", weight: 2 },
  { source: "印钞特抽", target: "胶正得分", weight: 2 },
  { source: "印钞特抽", target: "胶背得分", weight: 2 },
  { source: "印钞特抽", target: "凹正得分", weight: 2 },
  { source: "印钞特抽", target: "凹背得分", weight: 2 },
  { source: "印钞特抽", target: "印码得分", weight: 2 },
  { source: "印钞特抽", target: "裁切得分", weight: 2 },
  { source: "印钞特抽", target: "纸张得分", weight: 2 },
  { source: "印钞特抽", target: "评价总分", weight: 2 },
  { source: "印钞特抽", target: "安全线1", weight: 2 },
  { source: "印钞特抽", target: "竖号码", weight: 2 },
  { source: "印钞特抽", target: "OVMI", weight: 2 },
  { source: "防伪指标", target: "冠字号", weight: 2 },
  { source: "防伪指标", target: "W信号", weight: 1 },
  { source: "防伪指标", target: "荧光亮度", weight: 1 },
  { source: "防伪指标", target: "SM值", weight: 1 },
  { source: "防伪指标", target: "磁性", weight: 1 },
  { source: "防伪指标", target: "安全线2", weight: 1 },
  { source: "胶凹离线检测", target: "大万号", weight: 3 },
  { source: "胶凹离线检测", target: "人员类型", weight: 1 },
  { source: "胶凹离线检测", target: "机长3", weight: 1 },
  { source: "胶凹离线检测", target: "机台", weight: 1 },
  { source: "胶凹离线检测", target: "检测时间", weight: 1 },
  { source: "胶凹离线检测", target: "总分", weight: 1 },
  { source: "胶凹离线检测", target: "墨色", weight: 1 },
  { source: "胶凹离线检测", target: "接线", weight: 1 },
  { source: "胶凹离线检测", target: "套印", weight: 1 },
  { source: "胶凹离线检测", target: "混色", weight: 1 },
  { source: "胶凹离线检测", target: "防复印圈", weight: 1 },
  { source: "胶凹离线检测", target: "对印", weight: 1 },
  { source: "图像判废", target: "大万号", weight: 1 },
  { source: "图像判废", target: "印码号1", weight: 1 },
  { source: "图像判废", target: "人工实废", weight: 1 },
  { source: "图像判废", target: "机检实废", weight: 1 },
  { source: "图像判废", target: "机检误废", weight: 1 },
  { source: "图像判废", target: "实废大张", weight: 1 },
  { source: "图像判废", target: "未检数", weight: 1 },
  { source: "图像判废", target: "实废小开", weight: 1 },
  { source: "图像判废", target: "拆包量", weight: 1 },
  { source: "图像判废", target: "实废图像1", weight: 1 },
  { source: "号码三合一", target: "大万号", weight: 1 },
  { source: "号码三合一", target: "印码号2", weight: 1 },
  { source: "号码三合一", target: "冠字号", weight: 1 },
  { source: "号码三合一", target: "实废图像2", weight: 1 },
  { source: "号码三合一", target: "荧光缺陷2", weight: 1 },
  { source: "号码三合一", target: "号码缺陷2", weight: 1 },
  { source: "号码三合一", target: "实废类型1", weight: 1 },
  { source: "号码三合一", target: "实废数1", weight: 1 },
  { source: "号码三合一", target: "漏废数1", weight: 1 },
  { source: "机台作业", target: "大万号", weight: 1 },
  { source: "机台作业", target: "生产信息", weight: 1 },
  { source: "机台作业", target: "物料信息", weight: 1 },
  { source: "物料信息", target: "印版/色模", weight: 1 },
  { source: "物料信息", target: "油墨", weight: 1 },
  { source: "物料信息", target: "耗材", weight: 1 },
  { source: "印版/色模", target: "编号", weight: 1 },
  { source: "印版/色模", target: "印量", weight: 1 },
  { source: "油墨", target: "批次", weight: 1 },
  { source: "油墨", target: "名称", weight: 1 },
  { source: "油墨", target: "用量", weight: 1 },
  { source: "生产信息", target: "机长4", weight: 1 },
  { source: "生产信息", target: "机型", weight: 1 },
  { source: "生产信息", target: "班组", weight: 1 },
  //   { source: "生产信息", target: "生产时间", weight: 1 },
  { source: "生产信息", target: "冠字", weight: 1 },
  { source: "生产信息", target: "产量", weight: 1 },
  { source: "生产信息", target: "班次", weight: 1 },
  { source: "生产信息", target: "作业记录", weight: 1 },
  { source: "生产信息", target: "工序1", weight: 1 },
  { source: "质量综合管理系统", target: "码后核查", weight: 4 },
  { source: "质量综合管理系统", target: "小张核查", weight: 4 },
  { source: "质量综合管理系统", target: "大万号", weight: 4 },
  { source: "小张核查", target: "印码号4", weight: 1 },
  { source: "码后核查", target: "印码号5", weight: 1 },
  { source: "码后核查", target: "好品率1", weight: 1 },
  { source: "码后核查", target: "缺陷条数1", weight: 1 },
  { source: "码后核查", target: "核查剔废率1", weight: 1 },
  { source: "码后核查", target: "正面缺陷1", weight: 1 },
  { source: "码后核查", target: "背面缺陷1", weight: 1 },
  { source: "码后核查", target: "透视缺陷1", weight: 1 },
  { source: "码后核查", target: "荧光缺陷1", weight: 1 },
  { source: "码后核查", target: "号码缺陷1", weight: 1 },
  { source: "码后核查", target: "开位1", weight: 1 },
  { source: "码后核查", target: "宏区编号1", weight: 1 },
  { source: "码后核查", target: "黑图数1", weight: 1 },
  { source: "码后核查", target: "未检数1", weight: 1 },
  { source: "码后核查", target: "大张废1", weight: 1 },
  { source: "小张核查", target: "黑图数2", weight: 1 },
  { source: "小张核查", target: "未检数2", weight: 1 },
  { source: "小张核查", target: "好品率2", weight: 1 },
  { source: "小张核查", target: "缺陷条数2", weight: 1 },
  { source: "小张核查", target: "核查剔废率2", weight: 1 },
  { source: "小张核查", target: "冠字号2", weight: 1 },
  { source: "小张核查", target: "正面缺陷2", weight: 1 },
  { source: "小张核查", target: "背面缺陷2", weight: 1 },
  { source: "小张核查", target: "透视缺陷2", weight: 1 },
  { source: "小张核查", target: "开位2", weight: 1 },
  { source: "小张核查", target: "宏区编号2", weight: 1 },
  { source: "小张核查", target: "大张废2", weight: 1 },

  { source: "大万号", target: "印钞装箱系统", weight: 1 },
  { source: "印钞装箱系统", target: "箱号", weight: 3 },
  { source: "印钞装箱系统", target: "首张印码号", weight: 3 },
  { source: "印钞装箱系统", target: "装箱时间", weight: 3 },
  { source: "印钞装箱系统", target: "装箱机台", weight: 3 },

  { source: "大万号", target: "OCR系统", weight: 1 },
  { source: "冠字号", target: "OCR系统", weight: 1 },
  { source: "OCR系统", target: "识码时间", weight: 3 },
  { source: "OCR系统", target: "实际开包量", weight: 3 },
  { source: "OCR系统", target: "多取出数", weight: 3 },
  { source: "OCR系统", target: "未取出数", weight: 3 },
  { source: "OCR系统", target: "缺陷开数", weight: 3 },

  { source: "大万号", target: "在线清数", weight: 1 },
  { source: "在线清数", target: "喷码号", weight: 3 },
  { source: "在线清数", target: "抽样张数", weight: 3 },

  { source: "大万号", target: "凹印在线检测", weight: 1 },
  { source: "机台作业", target: "清分机检", weight: 1 },

  { source: "工艺质量管理平台", target: "轴号", weight: 5 },
  { source: "工艺质量管理平台", target: "大万号", weight: 5 },

  { source: "轴号", target: "钞纸机检", weight: 5 },
  { source: "轴号", target: "钞纸工艺", weight: 5 },

  { source: "钞纸工艺", target: "物理站", weight: 1 },
  { source: "钞纸工艺", target: "化验站", weight: 1 },
  { source: "印钞特抽", target: "机读防伪指标", weight: 1 },
  { source: "印钞特抽", target: "检封裁切人工评分", weight: 1 },
  { source: "钞纸工艺", target: "外观指标", weight: 1 },
  { source: "钞纸工艺", target: "机检在线抽查", weight: 1 },
  { source: "钞纸工艺", target: "损纸误废", weight: 1 },
  { source: "钞纸工艺", target: "批量报废", weight: 1 },
  { source: "钞纸工艺", target: "过程质量控制水平", weight: 1 },
  { source: "钞纸机检", target: "切纸机生产原始信息", weight: 1 },
  { source: "钞纸机检", target: "纸机好纸率", weight: 1 },
  { source: "钞纸机检", target: "切纸机好纸率", weight: 1 },
  { source: "钞纸机检", target: "纸机好纸数", weight: 1 },
  { source: "钞纸机检", target: "切纸机好纸数", weight: 1 },
  { source: "钞纸机检", target: "一次封包率", weight: 1 },
  { source: "钞纸机检", target: "切纸机异常品数", weight: 1 },
  { source: "钞纸机检", target: "返工率", weight: 1 }
];

nodes = nodes.map((item, i) => {
  item.id = i;
  return item;
});
links = links.map((item, i) => {
  item.id = i;
  return item;
});

links = links.map(item => {
  let source = nodes.find(node => node.name == item.source);
  let target = nodes.find(node => node.name == item.target);
  item.source = source ? source.id : "";
  item.target = target ? target.id : "";
  return item;
});

const option = {
  backgroundColor: "#313640",
  // 默认色板
  color: [
    "#61A5E8",
    "#7ECF51",
    "#EECB5F",
    "#E4925D",
    "#E16757",
    "#9570E5",
    "#605FF0",
    "#85ca36",
    "#1c9925",
    "#0d8b5f",
    "#0f9cd3",
    "#2f7e9b",
    "#2f677d",
    "#9b7fed",
    "#7453d6",
    "#3b1d98",
    "#27abb1",
    "#017377",
    "#015f63",
    "#b86868",
    "#5669b7",
    "#e5aab4",
    "#60b65f",
    "#98d2b2",
    "#c9c8bc",
    "#45c3dc",
    "#e17979",
    "#5baa5a",
    "#eaccc2",
    "#ffaa74"
  ],
  title: {
    text: "成都印钞有限公司\n生产、质量、数字信息力导向布局图",
    subtext: "截止至2018年3月",
    x: "right",
    y2: "0px",
    textStyle: {
      color: "#eee"
    },
    subtextStyle: {
      color: "#eee"
    }
  },
  tooltip: {
    trigger: "item",
    formatter: "{a} : {b}"
  },
  legend: {
    x: "left",
    data: ["主数据", "信息系统", "基础信息", "元信息"],
    selected: {
      主数据: false,
      元信息: false
    },
    textStyle: {
      color: "#eee"
    }
  },
  series: [
    {
      type: "graph",
      layout: "force",
      name: "节点描述",
      ribbonType: false,
      categories: [
        {
          name: "主数据"
        },
        {
          name: "信息系统"
        },
        {
          name: "元信息"
        },
        {
          name: "基础信息"
        }
      ],
      itemStyle: {
        color: "#eee",
        normal: {
          label: {
            show: true
          },
          nodeStyle: {
            brushType: "both",
            borderColor: "rgba(255,215,0,0.6)",
            borderWidth: 1
          }
        }
      },
      lineStyle: {
        normal: {
          color: "source",
          curveness: 0.3
        }
      },
      roam: true,
      label: {
        show: true,
        color: "#eee",
        position: "inside"
      },
      force: {
        repulsion: 100
      },
      nodes,
      links,
      symbolSize: item => item * 5
    }
  ]
};

export default option;
